### ISSUE TITLE
Can only call returns on a property once

### ISSUE THREAD

**Issue by vigie** [ffMathy/FluffySpoon.JavaScript.Testing.Faking#96] opened 2020-04-10 23:25 UTC
```
class Foo {
   get bar() {
      return 'bar';
   }
}

const fooSub = Substitute.for<Foo>();

fooSub.bar.returns('bar'); // OK

fooSub.bar.returns('baz'); // Error - returns is undefined.
```

This makes sense - in the second instance the value of `fooSub.bar` will be `'bar'`.

This may be by design, but I'm unsure of the best way to work around this problem.

I know you can set up multiple return values in a single call to returns, but that is not suited to my use case, where I want to introduce some default behavior in a set-up function but then later override the default returned value in an individual `it`.

Please advise, thanks!

**Comment by vigie** [comment] 2020-04-11 06:48
Is this related to https://github.com/ffMathy/FluffySpoon.JavaScript.Testing.Faking/issues/46 ? (just left a comment there as well)

**Comment by notanengineercom** [comment] 2020-04-11 23:14
It’s like that by design. I guess the only solution is to implement a way to reset specific mocks. What do you think about this? @ffMathy

**Comment by ffMathy** [comment] 2020-04-12 08:27
What is the use case here? Why would you ever want this? I feel this is a smell in your test. Why not two individual tests instead?

Tests should preferably only test one thing.

**Comment by ffMathy** [comment] 2020-04-12 11:13
Closing in favor of #46, but I'm starting to see what you mean.

**Comment by ffMathy** [comment] 2020-04-12 11:13
Will reply there.

**Closed by ffMathy** 2020-04-12 11:13 UTC
