### ISSUE TITLE
Keep targeting ES5 

### ISSUE THREAD

**Issue by jussimattila** [ffMathy/FluffySpoon.JavaScript.Testing.Faking#105] opened 2020-04-28 10:36 UTC
I updated to latest version (1.133.0) and my build pipeline stopped working. I found the reason is that you recently started targeting ES2016 instead of ES5. Is this intentional? I still need to support ES5 and I wouldn't like to add additional transpilers to my build pipeline just to use the latest version of this library.

https://github.com/ffMathy/FluffySpoon.JavaScript.Testing.Faking/commit/cb45abcb246681a6024cf1ff9bb396634d20be17#diff-e5e546dd2eb0351f813d63d1b39dbc48R14

**Comment by ffMathy** [comment] 2020-04-28 11:00
What error are you receiving in your build pipeline?

**Comment by jussimattila** [comment] 2020-04-28 11:02
```
ERROR in vendors~suite.js from UglifyJs 
Unexpected token: keyword (const)
```
I know UglifyJs only supports ES5, where `const` is not allowed. But I have tons of packages in the solution and this one is the only one not providing ES5 JavaScript.

**Comment by jussimattila** [comment] 2020-04-28 12:49
And if you have good reasons for changing targets, of course you can do that! Testing code should not have an impact on the supported app runtime environments. I came across this issue only because our build pipeline didn't handle es6+ features even for development/testing environments.

**Comment by ffMathy** [comment] 2020-04-28 12:51
@jussimattila I think we should run on an as low ES target as possible.

I actually can't seem to see why it was changed. @notanengineercom perhaps you have an idea of this?

A recommendation in general though, is to run your build process inside Docker on the build server. That may serve as a workaround until we fix the issue.

**Comment by jussimattila** [comment] 2020-04-28 12:57
The build process runs inside Docker already. Our problem was that JavaScript minification was run also for test code using uglifyjs-webpack-plugin (which has been recently deprecated, I just found out). As mentioned above, UglifyJS supports only ES5 code. Anyways, in our case, disabling minification for test builds was a simple workaround. But I definitely agree that it is better to target as low ES version as possible.

**Comment by notanengineercom** [comment] 2020-04-28 17:14
I bumped the target as some functions were not available using ES5. https://github.com/ffMathy/FluffySpoon.JavaScript.Testing.Faking/pull/91
Also proxies (which are the base of this library) were introduced in ES6, which means all standards before that one can't use proxy. Babel can't transpile it (https://babeljs.io/docs/en/learn#proxies), and it's only partially transpileable by some specific libraries.

Sorry for being curious, but what is the reasoning of passing the actual test code on an uglifier / minifier?
As you are using uglifyjs-webpack-plugin, can you not use the uderlying Babel to transpile ES6+ syntax to ES5 one?

**Comment by jussimattila** [comment] 2020-04-28 18:41
I already moved to `terser-webpack-plugin` after learning `uglifyjs-webpack-plugin` was deprecated some months ago. I have no reasoning for minifying test code, except that there are so many moving parts in the JavaScript ecosystem. The webpack config we had was working great in local/CI with dev/prod support and I didn't even consider it was minifying test code, since I was able to debug it just fine.  ¯\_(ツ)_/¯

Like I said, if you do need ES6, go ahead and use it. We adapt, like we always do when npm dependencies are updated! 😄

**Comment by notanengineercom** [comment] 2020-05-05 22:14
Hey sorry for the delay!
I'm really glad that you could sort the issue out! Thank you for using it, I'm sure I speak for the both of us when I say that I'm glad you love the library 😄 
I'm testing locally if everything works as intended using ES6. If it does, I'll lower the target. That's the lowest we can support.
Closing this now!

**Closed by notanengineercom** 2020-05-05 22:14 UTC
