### ISSUE TITLE
Mocking a method with an array as an argument fails

### ISSUE THREAD

**Issue by dcavanagh** [ffMathy/FluffySpoon.JavaScript.Testing.Faking#10] opened 2018-10-15 16:58 UTC
I am trying to mock a method that accepts an array as an argument. There is something wrong with the argument matching
```ts
interface Calculator {
    add(a: number[]): number[];
}

let calculator = Substitute.for<Calculator>();
calculator.add([1, 2]);
calculator.received().add([1, 2]); // fails
calculator.recieved().add(Arg.any()); // succeeds
```
Error Message:
Error: Expected one or more calls to the method add with arguments [1,2], but received none of such calls.
All calls received to method add:
-> 1 call with no arguments
-> 1 call with arguments [1,2]

**Comment by ffMathy** [comment] 2018-10-24 06:56
I made a branch now called `progress` where I am refactoring the whole thing into being based on a strategy pattern.

You can follow up on the progress there. However, I don't have much time lately. Feel free to fork that branch and continue.

**Comment by dcavanagh** [comment] 2018-10-26 17:51
@ffMathy i'm not seeing the branch.  thanks

**Comment by ffMathy** [comment] 2018-10-27 14:09
That's because it has been merged now.

**Comment by ffMathy** [comment] 2018-10-27 14:11
Wait, what you reported is actually not a bug! I see that now...

Arrays are by reference - not by value comparisons.

So instead of:

```
let calculator = Substitute.for<Calculator>();
calculator.add([1, 2]);
calculator.received().add([1, 2]); // fails
calculator.recieved().add(Arg.any()); // succeeds
```

Do:

```
let calculator = Substitute.for<Calculator>();
const myArray = [1, 2];
calculator.add(myArray);
calculator.received().add(myArray); // succeeds
calculator.recieved().add(Arg.any()); // succeeds
```

**Closed by ffMathy** 2018-10-27 14:11 UTC

**Comment by dcavanagh** [comment] 2018-11-05 14:12
@ffMathy Thanks!
