### ISSUE TITLE
Can't mimick AWS SNS.publish

### ISSUE THREAD

**Issue by cfredhart** [ffMathy/FluffySpoon.JavaScript.Testing.Faking#93] opened 2020-04-10 06:04 UTC
I'm trying to call my callback when I call `publish` on a Substituted AWS `SNS` instance. My code looks something like the sample below, but `sns.publish(Arg.any('object'),Arg.any())` doesn't seem to have the `mimick` method. I've played around with the argument matching and can't seem to get this to work. I don't know if this is an issue or a lack of understanding on my part.
```
import { SNS, AWSError } from 'aws-sdk';
import { Request } from 'aws-sdk/lib/request';
import { Substitute, Arg } from '@fluffy-spoon/substitute';

const sns = Substitute.for<SNS>();
function callback (data: SNS.PublishInput) {
    const snsResponse = Substitute.for<Request<SNS.PublishResponse, AWSError>>();
    console.log(`data=${data}, snsResponse=${snsResponse}`);
    return snsResponse;
}
sns.publish(Arg.any('object'),Arg.any()).mimicks(callback);
```

Ultimately what I want to do is to simulate different behavior/responses from my mocked `publish` method based on what was passed in the first parameter to the call to `publish` (which is of type `SNS.PublishInput`) I cannot also figure out how to check that a certain input was passed to `publish`. When I try to pass an object that adheres to the `SNS.PublishInput` interface to the   `received().publish()` check below

```
sns.received().publish(publishInput)
```
results in the following compiler error. I'm trying to verify that a particular input is passed to the `publish` call by the software under test.
```
error TS2769: No overload matches this call.
  Overload 1 of 2, '(callback?: ((err: AWSError, data: PublishResponse) => void) | undefined): void', gave the following error.
    Argument of type 'PublishInput' is not assignable to parameter of type '(err: AWSError, data: PublishResponse) => void'.
      Type 'PublishInput' provides no match for the signature '(err: AWSError, data: PublishResponse): void'.
  Overload 2 of 2, '(arg: AllArguments): void', gave the following error.
    Argument of type 'PublishInput' is not assignable to parameter of type 'AllArguments'.
      Type 'PublishInput' is missing the following properties from type 'AllArguments': description, matchingFunction, matches
```

**Comment by notanengineercom** [comment] 2020-04-10 15:21
This is due to a Typescript limitation where when inferring a function parameter or return type, the last overload is used for inferrence, as it is assumed to be the general one.

But I'm working on a workaround - it should cover most cases, but maybe not all of them. I think it will fix your case, as sns.publish only has two function overloads.

**Comment by notanengineercom** [comment] 2020-04-10 19:18
@cfredhart, thanks for all the info! In the pr I just submitted, the issue is fixed with a workaround. I tested both cases you provided, and can verify that typescript won't complain anymore. As I explain in the pull request, the origin of the issue is a typescript limitation

> When inferring from a type with multiple call signatures (such as the type of an overloaded function), inferences are made from the last signature (which, presumably, is the most permissive catch-all case). It is not possible to perform overload resolution based on a list of argument types.
[Link to quoute in documentation](
https://www.typescriptlang.org/docs/handbook/advanced-types.html#type-inference-in-conditional-types)

**Closed** 2020-04-10 21:18 UTC
